UI rework
Frede175/Gruppe13 pull request #52
Opened 2018-05-24 10:07 UTC by Frede175

2018-05-24 10:41 UTC, larsbjn requested changes

2018-05-24 10:41 UTC, larsbjn commented on SensumUdred_UI/src/ui/TimeChecker.java
>                  //sleeps for 1/2 a second each time..
1 second

2018-05-24 15:51 UTC, larsbjn submitted a review, later dismissed

2018-05-25 09:32 UTC, Sebastianchr22 submitted a review, later dismissed

2018-05-26 15:14 UTC, krongrah approved these changes

2018-05-27 09:32 UTC, larsbjn approved these changes

2018-05-27 09:33 UTC, merged